In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_employee_data.csv")

In [3]:
df

   EmployeeID    Name   Age   Gender Department   Salary JoiningDate
0         101     Ali  25.0     male         IT  50000.0  2021-05-10
1         102    Sara   NaN   Female         HR  45000.0  2020/08/15
2         103    John  30.0     Male         it  60000.0  2019-11-20
3         104  Ayesha  28.0   FEMALE    Finance      NaN  2022-01-05
4         105   Rahul  35.0  unknown         HR  55000.0         NaN

In [5]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   5 non-null      int64
 1   Name         5 non-null      object
 2   Age          4 non-null      float64
 3   Gender       5 non-null      object
 4   Department   5 non-null      object
 5   Salary       4 non-null      float64
 6   JoiningDate  4 non-null      object
dtypes: float64(2), int64(1), object(4)
memory usage: 412.0+ bytes

EmployeeID     0
Name           0
Age            1
Gender         0
Department     0
Salary         1
JoiningDate    1
dtype: int64

In [8]:
# first clean col names
df.columns = df.columns.str.strip().str.lower()
df

   employeeid    name   age   gender department   salary joiningdate
0         101     Ali  25.0     male         IT  50000.0  2021-05-10
1         102    Sara   NaN   Female         HR  45000.0  2020/08/15
2         103    John  30.0     Male         it  60000.0  2019-11-20
3         104  Ayesha  28.0   FEMALE    Finance      NaN  2022-01-05
4         105   Rahul  35.0  unknown         HR  55000.0         NaN

In [15]:
# handle missing values
df["age"] = df["age"].fillna(df["age"].median())
df["salary"] = df["salary"].fillna(df["salary"].mean())
df["joiningdate"] = df["joiningdate"].fillna("Unknown")
df

   employeeid    name   age   gender department   salary joiningdate
0         101     Ali  25.0     male         IT  50000.0  2021-05-10
1         102    Sara  29.0   Female         HR  45000.0  2020/08/15
2         103    John  30.0     Male         it  60000.0  2019-11-20
3         104  Ayesha  28.0   FEMALE    Finance  52500.0  2022-01-05
4         105   Rahul  35.0  unknown         HR  55000.0     Unknown

In [22]:
# clean text data
df["gender"] = df["gender"].str.strip().str.title()
df["department"] = df["department"].str.strip().str.title()
df

   employeeid    name   age   gender department   salary joiningdate
0         101     Ali  25.0     Male         It  50000.0  2021-05-10
1         102    Sara  29.0   Female         Hr  45000.0  2020/08/15
2         103    John  30.0     Male         It  60000.0  2019-11-20
3         104  Ayesha  28.0   Female    Finance  52500.0  2022-01-05
4         105   Rahul  35.0  Unknown         Hr  55000.0     Unknown

In [25]:
# standarised gender
gender_map = {
    "Male": "M",
    "Female": "F",
    "Unknown": "U"
}

df["gender"] = df["gender"].apply(lambda x: gender_map.get(x, x))
df

   employeeid    name   age gender department   salary joiningdate
0         101     Ali  25.0      M         It  50000.0  2021-05-10
1         102    Sara  29.0      F         Hr  45000.0  2020/08/15
2         103    John  30.0      M         It  60000.0  2019-11-20
3         104  Ayesha  28.0      F    Finance  52500.0  2022-01-05
4         105   Rahul  35.0      U         Hr  55000.0     Unknown

In [28]:
# create new col
df = df.assign(
    tax = df["salary"] * 0.1,
    net_salary = df["salary"] - (df["salary"] * 0.1)
)
df

,employeeid,name,age,gender,department,salary,joiningdate,tax,net_salary
0,101,Ali,25.0,M,It,50000.0,2021-05-10,5000.0,45000.0
1,102,Sara,29.0,F,Hr,45000.0,2020/08/15,4500.0,40500.0
2,103,John,30.0,M,It,60000.0,2019-11-20,6000.0,54000.0
3,104,Ayesha,28.0,F,Finance,52500.0,2022-01-05,5250.0,47250.0
4,105,Rahul,35.0,U,Hr,55000.0,Unknown,5500.0,49500.0

In [32]:
# sorting based on salary
df = df.sort_values("salary", ascending=False)
df

,employeeid,name,age,gender,department,salary,joiningdate,tax,net_salary
2,103,John,30.0,M,It,60000.0,2019-11-20,6000.0,54000.0
4,105,Rahul,35.0,U,Hr,55000.0,Unknown,5500.0,49500.0
3,104,Ayesha,28.0,F,Finance,52500.0,2022-01-05,5250.0,47250.0
0,101,Ali,25.0,M,It,50000.0,2021-05-10,5000.0,45000.0
1,102,Sara,29.0,F,Hr,45000.0,2020/08/15,4500.0,40500.0

In [33]:
# save clean data
df.to_csv("cleaned_employee_data.csv", index=False)